# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11a1b5263c2975302ca5c0ce5b97aefffa0f5f0ee41538615afd4d451bc7a8f1eb9d567921ea49fd78b317b11d8bbed9becdf3e9343007c90aacbaef4b1a9ffc

test:
  secret_key_base: abf461b2fbc0557058b176f47ee9fc92eee532da80a8fd46da3552133c15dcc5fe3a4f466f9b5fc2b4716331d3afb0bdc14e75f7dbda8ae26eae55382c01c3a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
